sudo: required
dist: xenial

language: generic

install:
- sudo apt-add-repository -y ppa:octave/stable
- sudo apt-get update -qq
- sudo apt-get install -qq octave liboctave-dev

env:
- MP_PATH=$TRAVIS_BUILD_DIR/lib
- MP_PATH=$MP_PATH:$TRAVIS_BUILD_DIR/lib/t
- MP_PATH=$MP_PATH:$TRAVIS_BUILD_DIR/mptest/lib
- MP_PATH=$MP_PATH:$TRAVIS_BUILD_DIR/mptest/lib/t
- MP_PATH=$MP_PATH:$TRAVIS_BUILD_DIR/mips/lib
- MP_PATH=$MP_PATH:$TRAVIS_BUILD_DIR/mips/lib/t
- MP_PATH=$MP_PATH:$TRAVIS_BUILD_DIR/most/lib
- MP_PATH=$MP_PATH:$TRAVIS_BUILD_DIR/most/lib/t

script:
- octave -p $MP_PATH --eval test_matpower
- octave -p $MP_PATH --eval test_most
