sudo: required
dist: xenial

language: generic

install:
- sudo apt-add-repository -y ppa:octave/stable
- sudo apt-get update -qq
- sudo apt-get install -qq octave liboctave-dev git make coinor-libipopt-dev

- git clone https://github.com/yalmip/YALMIP.git yalmip
- octave-cli --no-gui --eval "addpath(genpath('$TRAVIS_BUILD_DIR/yalmip'));savepath"
- octave-cli --no-gui --eval "path"

- git clone https://github.com/sqlp/sdpt3.git sdpt3
- (cd sdpt3 && octave-cli --no-gui --eval "install_sdpt3('-rebuild')")

- git clone https://github.com/sqlp/sedumi.git sedumi
- (cd sedumi && octave-cli --no-gui --eval "install_sedumi('-rebuild')")

- git clone https://github.com/rwl/ipopt.git ipopt
- make -C ipopt
- octave-cli --no-gui --eval "addpath(genpath('$TRAVIS_BUILD_DIR/ipopt'));savepath"
- octave-cli --no-gui --eval "path"

script:
- octave-cli --no-gui --eval ver
- octave-cli --no-gui --eval "install_matpower(1,1,1)";
- octave-cli --no-gui --eval mpver
- octave-cli --no-gui --eval "test_mptest(0,1)"
- octave-cli --no-gui --eval "test_mips(0,1)"
- octave-cli --no-gui --eval "test_matpower(0,1)"
- octave-cli --no-gui --eval "test_most(0,1)"

- octave-cli --no-gui --eval "t_opf_dc_glpk;t_opf_dc_ipopt;t_opf_ipopt"

- octave-cli --no-gui --eval "yalmiptest('sdpt3', 1)"
- octave-cli --no-gui --eval "yalmiptest('sedumi', 1)"

- octave-cli --no-gui --eval t_opf_sdpopf
- octave-cli --no-gui --eval t_insolvablepf_limitQ
- octave-cli --no-gui --eval t_insolvablepf
#- octave-cli --no-gui --eval t_insolvablepfsos_limitQ
- octave-cli --no-gui --eval t_insolvablepfsos
- octave-cli --no-gui --eval t_testglobalopt

- octave-cli --no-gui --eval "runsdpopf('case9', mpoption('yalmip.opts.solver', 'sdpt3', 'out.bus', 0, 'out.branch', 0))"
- octave-cli --no-gui --eval "runsdpopf('case9', mpoption('yalmip.opts.solver', 'sedumi', 'out.bus', 0, 'out.branch', 0))"
